[package]
name = "async-benchmarks"
version = "0.1.0"
authors = ["Vitor Enes <vitorenesduarte@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio", rev = "27e5b41067d01c0c9fac230c5addb58034201a63" }
async-std = "1.0.1"
num_cpus = "1.11.0"
